### ISSUE TITLE
command line code fix in second presentation 

### ISSUE THREAD

**Issue by PurplePegasuss** [GPrathap/ros2_intro#2]
![image](https://github.com/GPrathap/ros2_intro/assets/56448851/480a3fa7-1f72-4d97-a8d9-b2ce14bea220)

This slide in second presentation seems to contain code error:

`cd ../ && colcon build --packages-select hello_word` results in error:

`Starting >>> hello_world
[0.600s] ERROR:colcon.colcon_cmake.task.cmake.build:Failed to find the following files:
\- /home/mike/ros2_ws/install/friend_msgs/share/friend_msgs/package.sh
Check that the following packages have been built:
\- friend_msgs Failed   <<< hello_world [0.02s, exited with code 1]`

changing the line to `cd ../ && colcon build --packages-select hello_word friend_msgs `  or `cd ../ && colcon build` fixes an error.

**Comment by GPrathap** [comment]
Thanks, to fix the the error correctly use  `--packages-above-and-dependencies` , these are some recent `colcon` updates  (https://colcon.readthedocs.io/en/released/reference/package-selection-arguments.html)
